# Generated by Django 3.2.4 on 2021-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210618_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_name',
            name='ticker',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
