# Generated by Django 3.2.4 on 2021-06-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_name_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_name',
            name='ticker',
            field=models.CharField(max_length=200),
        ),
    ]
