# Generated by Django 3.2.4 on 2021-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_name_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_name',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_name',
            name='ticker',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
